version: '3.8'
services:
  indexer:
    image: avivabramovich/alpine-repository
    build:
      context: alpine_repo
      dockerfile: Dockerfile
  indexer-local:
    image: avivabramovich/alpine-repository
    volumes:
    - './tmp/repo:/mnt/repo'
    ports:
    - "5000:80"
    environment:
    - ALPINE_REPO_DRIVER=local
    - ALPINE_REPO_DRIVER_OPTIONS=path=/mnt/repo
    - ALPINE_REPO_CLEAN_ON_STARTUP=TRUE
    hostname: indexer
  indexer-local_trusted:
    image: avivabramovich/alpine-repository
    volumes:
    - './tmp/repo/x86_64:/mnt/repo'
    - './tmp/keys:/mnt/keys:ro'
    environment: 
    - DRIVER=local
    - DRIVER_OPTIONS='PATH="/mnt/repo",CLEAN_ON_STARTUP="TRUE",PRIV_KEY_PATH="/mnt/keys/test-keys@avivabramovich@gmail.com.rsa"'
    - LOG_LEVEL=DEBUG
    hostname: indexer
  indexer-remote-trusted:
    image: avivabramovich/alpine-repository
    ports:
    - '80:80'
    volumes:
    - './tmp/repo/x86_64:/mnt/repo'
    - './tmp/keys:/mnt/keys:ro'
    environment: 
    - PROXY=TRUE
    - PROXY_REPO_URL=http://172.17.0.1:8081/repository/test
    - PROXY_CREDENTIALS=aviv:1
    - PRIV_KEY_PATH=/mnt/keys/test-keys@avivabramovich@gmail.com.rsa
    - LOG_LEVEL=DEBUG
    hostname: indexer
  repo-httpd:
    image: httpd:2.4-alpine
    hostname: alpine-repo
    ports: 
    - 80:80
    volumes: 
    - "./tmp/repo:/usr/local/apache2/htdocs/:ro"
#  indexer_httpd:
#    image: avivabramovich/alpine-repository:httpd
#    build:
#      context: alpine_repo
#      dockerfile: httpd.Dockerfile
#    ports:
#    - '80:80'
#    - '5000:5000'
#    volumes:
#    - "./tmp/repo:/usr/local/apache2/htdocs/"
#    environment:
#    - CLEAN_ON_STARTUP=TRUE
  .tests:
    image: alpine
    environment: 
    - PACKAGE_NAME=bash
    - REPO_URL=http://alpine-repo
    volumes:
    - "./scripts:/scripts"
  test-upload:
    extends: .tests
    command: "sh /scripts/uploader.sh ${PACKAGE_NAME} indexer"
    depends_on:
    - indexer
  test-add-untrusted:
    extends: .tests
    command: 'sh -c "sh /scripts/configure-untrusted.sh ${REPO_URL} && apk add ${PACKAGE_NAME} --allow-untrusted"'
    depends_on: 
    - repo-httpd
  test-add-trusted:
    extends: .tests
    command: 'sh -c "sh /scripts/configure-trusted.sh ${REPO_URL} && apk add ${PACKAGE_NAME}"'
    depends_on: 
    - repo-httpd
