version: '3.8'
services: 
  indexer:
    image: avivabramovich/alpine-repository:indexer
    build:
      context: src
      dockerfile: Dockerfile
    volumes:
    - './tmp/repo/x86_64:/mnt/repo'
    environment: 
    - REPOISOTRY_PATH=/mnt/repo
    - CLEAN_ON_STRARTUP=TRUE
    hostname: indexer
  indexer_trusted:
    image: avivabramovich/alpine-repository:indexer
    volumes:
    - './tmp/repo/x86_64:/mnt/repo'
    - './tmp/keys:/mnt/keys:ro'
    environment: 
    - REPOISOTRY_PATH=/mnt/repo
    - CLEAN_ON_STRARTUP=TRUE
    - PRIV_KEY_PATH=/mnt/keys/test-keys@avivabramovich@gmail.com.rsa
    - LOG_LEVEL=DEBUG
    hostname: indexer
  repo-httpd:
    image: httpd:2.4-alpine
    hostname: alpine-repo
    ports: 
    - 80:80
    volumes: 
    - "./tmp/repo:/usr/local/apache2/htdocs/:ro"
  indexer_httpd:
    image: avivabramovich/alpine-repository:httpd
    build:
      context: src
      dockerfile: httpd.Dockerfile
    ports:
    - '80:80'
    - '5000:5000'
    volumes:
    - "./tmp/repo:/usr/local/apache2/htdocs/"
    environment: 
    - CLEAN_ON_STRARTUP=TRUE
  .tests:
    image: alpine
    environment: 
    - PACKAGE_NAME=bash
    - REPO_URL=http://alpine-repo
    volumes:
    - "./scripts:/scripts"
  test-upload:
    extends: .tests
    command: "sh /scripts/uploader.sh ${PACKAGE_NAME} indexer"
    depends_on:
    - indexer
  test-add-untrusted:
    extends: .tests
    command: 'sh -c "sh /scripts/configure-untrusted.sh ${REPO_URL} && apk add ${PACKAGE_NAME} --allow-untrusted"'
    depends_on: 
    - repo-httpd
  test-add-trusted:
    extends: .tests
    command: 'sh -c "sh /scripts/configure-trusted.sh ${REPO_URL} && apk add ${PACKAGE_NAME}"'
    depends_on: 
    - repo-httpd
